//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalProject {
    
    
    public partial class WebForm13 {
        
        /// <summary>
        /// userName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label userName;
        
        /// <summary>
        /// errorText control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label errorText;
        
        /// <summary>
        /// YES control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button YES;
        
        /// <summary>
        /// no control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button no;
        
        /// <summary>
        /// busName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label busName;
        
        /// <summary>
        /// edit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button edit;
        
        /// <summary>
        /// addFav control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button addFav;
        
        /// <summary>
<<<<<<< HEAD
        /// addFav control.
=======
        /// favText control.
>>>>>>> origin/master
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Button addFav;
        
        /// <summary>
        /// favText control.
=======
        protected global::System.Web.UI.WebControls.Label favText;
        
        /// <summary>
        /// logo control.
>>>>>>> origin/master
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Label favText;
        
        /// <summary>
        /// logo control.
=======
        protected global::System.Web.UI.WebControls.Image logo;
        
        /// <summary>
        /// category control.
>>>>>>> origin/master
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Image logo;
        
        /// <summary>
        /// category control.
=======
        protected global::System.Web.UI.WebControls.Label category;
        
        /// <summary>
        /// place control.
>>>>>>> origin/master
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.Label category;
=======
        protected global::System.Web.UI.WebControls.Label place;
>>>>>>> origin/master
        
        /// <summary>
        /// det control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label det;
        
        /// <summary>
        /// det control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label det;
        
        /// <summary>
<<<<<<< HEAD
        /// GridView1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        /// <summary>
        /// table1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView table1;
        
        /// <summary>
=======
>>>>>>> origin/master
        /// del control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button del;
    }
}
